name: Selenium Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size 2g -p 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: my-step
        run: echo $GITHUB_WORKSPACE

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Selenium container status
        run: docker ps

      - name: Run tests with Docker Selenium (Chrome)
        run: |
          pytest tests/ -v  --html=report.html

      - name: Upload test report and screenshots as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
              $GITHUB_WORKSPACE\report.html
          retention-days: 5
